=== FIWARE/data-models/OpenHealthContext/ClinicalControl/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://smartsdk.github.io/dataModels/OpenHealthContext/ClinicalControl/schema.json",
  "title": "FIWARE - Control-test schema",
  "description": "Represents a baseline measurement data for patients.",
  "type": "object",
  "references": [
    {
      "description": "Pending to be included.",
      "url": "Pending to be included."
    }
  ],
  "definitions": {
    "id": {
      "references": [
        {
          "description": "Unique value either created or provided from an entity to identify a single test. The SNOMED code represents an identifier (property).",
          "url": "http://purl.bioontology.org/ontology/SNOMEDCT/118522005"
        }
      ],
      "type": "string"
    },
    "type": {
      "description": "NGSI Entity type",
      "type": "string",
      "enum": [
        "ControlTest"
      ]
    },
    "refUser": {
      "type": "string",
      "format": "uri"
    },
    "bodyWeight": {
      "$ref": "http://www.openmhealth.org/schema/omh/body-weight-1.0.json#mass_unit_value"
    },
    "bodyHeight": {
      "$ref": "http://www.openmhealth.org/schema/omh/body-height-1.0.json#length_unit_value"
    },
    "waistCircumference": {
      "$ref": "http://www.openmhealth.org/schema/omh/length-unit-value-1.0.json"
    },
    "heartRate": {
      "$ref": "http://www.openmhealth.org/schema/omh/heart-rate-1.0.json"
    },
    "systolicBloodPressure": {
      "$ref": "http://www.openmhealth.org/schema/omh/systolic-blood-pressure-1.0.json"
    },
    "diastolicBloodPressure": {
      "$ref": "http://www.openmhealth.org/schema/omh/diastolic-blood-pressure-1.0.json"
    },
    "dateModified": {
      "type": "string",
      "format": "date-time"
    }
  },
  "properties": {
    "id": {
      "$ref": "#/definitions/id"
    },
    "type": {
      "$ref": "#/definitions/type"
    },
    "refUser": {
      "$ref": "#/definitions/refUser"
    },
    "omh:body_weight": {
      "$ref": "#/definitions/bodyWeight"
    },
    "omh:body_height": {
      "$ref": "#/definitions/bodyHeight"
    },
    "waistCircumference": {
      "$ref": "#/definitions/waistCircumference"
    },
    "omh:heart_rate": {
      "$ref": "#/definitions/heartRate"
    },
    "omh:systolic_blood_pressure": {
      "$ref": "#/definitions/systolicBloodPressure"
    },
    "omh:diastolic_blood_pressure": {
      "$ref": "#/definitions/diastolicBloodPressure"
    },
    "dateModified": {
      "$ref": "#/definitions/dateModified"
    }
  },
  "required": [
    "id",
    "type",
    "refUser",
    "omh:body_weight",
    "omh:body_height",
    "waistCircumference",
    "omh:heart_rate",
    "omh:systolic_blood_pressure",
    "omh:diastolic_blood_pressure",
    "dateModified"
  ]
}

=== FIWARE/data-models/OpenHealthContext/ClinicalControl/example.json
{
   "id": "ffffffffff9cbbf4465f0ef30033c587-control-4",
   "type": "ControlTest",
   "refUser": "http://207.249.127.162:1234/users/1",
   "omh:body_weight": {
      "value": "89",
      "unit": "kg"
   },
   "omh:body_height": {
      "value": "180",
      "unit": "cm"
   },
   "waistCircumference": {
      "value": "100",
      "unit": "cm"
   },
   "omh:heart_rate": {
      "value": "70",
      "unit": "beats/min"
   },
   "omh:systolic_blood_pressure": {
      "value": "120",
      "unit": "mmHg"
   },
   "omh:diastolic_blood_pressure": {
      "value": "120",
      "unit": "mmHg"
   },
   "dateModified": "2017-01-18T20:45:42.697Z"
}
